# Generated by Django 4.2.2 on 2023-06-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cali_User',
        ),
    ]
