# Generated by Django 4.2.2 on 2023-06-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_cali_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cali_User',
            new_name='User',
        ),
    ]
